version: '3.8'
# all the containers have to declare inside services
services:
  # App service
  colkie:
    # this build context will take the commands from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # image name
    image: test-colkie
    # container name
    container_name: colkie
    # always restart the container if it stops.
    restart: always
    # docker run -t is allow
    tty: true
    # application port, this is take value from env file
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # working directory
    working_dir: /var/www/test-colkie
    # application environment
    environment:
      SERVICE_NAME: colkie
      SERVICE_TAGS: ${NODE_ENV}
    # save (persist) data and also to share data between containers
    volumes:
      - ./:/var/www/test-colkie
      - /var/www/test-colkie/node_modules
      # application network, each container for a service joins this network
    networks:
      - colkie-network
  
#Docker Networks
networks:
  # All container connect in a network
  colkie-network:
    driver: bridge
