version: '3.8'
services:
  # DB service
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - colkie-network
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports: 
      - 5400:${POSTGRES_DB_PORT}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  # postgres-test:
  #   container_name: postgres-test
  #   image: postgres:latest
  #   networks:
  #     - colkie-network
  #   environment: 
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_USER: test
  #     POSTGRES_DB: test
  #   depends_on: 
  #     - postgres
  #   ports: 
  #     - 5401:${POSTGRES_DB_PORT}
  #   restart: always
  #   volumes:
  #     - pgdata-test:/var/lib/postgresql/data    

  # App service
  colkie:
    container_name: colkie
    image: test-colkie
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
      # - postgres-test
    env_file:
      - .env
    restart: always
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    working_dir: /var/www/test-colkie
    environment:
      SERVICE_NAME: colkie
      ENV: ${NODE_ENV} 
      PORT: ${SERVER_PORT}
    volumes:
      - ./:/var/www/test-colkie
      - app:/var/www/test-colkie/node_modules
    networks:
      - colkie-network

networks:
  colkie-network:
    driver: bridge

volumes:
  pgdata:
  # pgdata-test:
  app:
